# Generated by Django 4.2.2 on 2024-01-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(auto_now_add=True, verbose_name='datea')),
                ('title', models.CharField(max_length=255, verbose_name='application_title')),
                ('details', models.TextField(verbose_name='application_details')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['datea'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='city_title')),
            ],
            options={
                'db_table': 'city',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price_min')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price_max')),
            ],
            options={
                'db_table': 'concert',
                'ordering': ['datec'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64, verbose_name='place')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('datet', models.DateTimeField(auto_now_add=True, verbose_name='datet')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_concert', to='concert.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['datet'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(verbose_name='datem')),
                ('status', models.CharField(max_length=128, verbose_name='movement_status')),
                ('details', models.TextField(blank=True, null=True, verbose_name='movement_details')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_application', to='concert.application')),
            ],
            options={
                'db_table': 'movement',
                'ordering': ['datem'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='hall_title')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='hall_photo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_city', to='concert.city')),
            ],
            options={
                'db_table': 'hall',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateg', models.DateTimeField(verbose_name='dateg')),
                ('title', models.CharField(max_length=256, verbose_name='gallery_title')),
                ('details', models.TextField(verbose_name='gallery_details')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='gallery_photo')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='gallery_photo')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='gallery_photo')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='gallery_photo')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='gallery_photo')),
            ],
            options={
                'db_table': 'gallery',
                'ordering': ['dateg'],
                'indexes': [models.Index(fields=['dateg'], name='gallery_dateg_b4e795_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entertainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='entertainer_name')),
                ('details', models.TextField(verbose_name='entertainer_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='entertainer_photo')),
            ],
            options={
                'db_table': 'entertainer',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='entertainer_name_1e164b_idx')],
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='entertainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_entertainer', to='concert.entertainer'),
        ),
        migrations.AddField(
            model_name='concert',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_hall', to='concert.hall'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['title'], name='city_title_fcc479_idx'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['concert'], name='ticket_concert_746c93_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user'], name='ticket_user_id_2d9e10_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['datet'], name='ticket_datet_188690_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['application'], name='movement_applica_27871b_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['datem'], name='movement_datem_8708fe_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['city'], name='hall_city_id_b02ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['title'], name='hall_title_44be5f_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['datec'], name='concert_datec_4aa355_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['entertainer'], name='concert_enterta_dab040_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['hall'], name='concert_hall_id_280abe_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['datea'], name='application_datea_198fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_ba75f5_idx'),
        ),
    ]
